# Measure elapsed time
typeset -F SECONDS

# Define framework location
ZSH="${ZDOTDIR:-${HOME}}/.zsh"
if [[ -s "${HOME}/.zplug" ]]; then
    echo ".zsh directory is missing"
fi

# Debug
# set -x

##
# Version Check
#

# Check for the minimum supported version.
min_zsh_version='4.3.17'
if ! autoload -Uz is-at-least || ! is-at-least "$min_zsh_version"; then
    printf "dotzsh: old shell detected, minimum required: %s\n" "$min_zsh_version" >&2
    return 1
fi
unset min_zsh_version

pfunction_glob='^([_.]*|prompt_*_setup|README*)(-.N:t)'

export ZPLUG_HOME="/usr/local/opt/zplug"

if [[ ! -s "${ZPLUG_HOME}/init.zsh" ]]; then
    print "Requires zplug, please install it first."
    return 1
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zconfig" ]]; then
    source "${ZDOTDIR:-$HOME}/.zconfig"
fi

# Disable color and theme in dumb terminals.
if [[ "$TERM" == 'dumb' ]]; then
    zstyle ':dotzsh:*:*' color 'no'
    zstyle ':dotzsh:module:prompt' theme 'off'
else
    export TERM="xterm-256color"
fi

export ZPLUG_LOADFILE="${ZDOTDIR:-$HOME}/.zsh/zplug.zsh"
source "${ZPLUG_HOME}/init.zsh"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
    echo
fi

zplug load
# zplug load --verbose

# Print elapsed time
echo "${SECONDS}s elapsed"

unset pfunction_glob
