export ZPLUG_HOME="/usr/local/opt/zplug"

if [[ -s "${ZDOTDIR:-$HOME}/.zconfig" ]]; then
    source "${ZDOTDIR:-$HOME}/.zconfig"
fi

# Disable color and theme in dumb terminals.
if [[ "$TERM" == 'dumb' ]]; then
    zstyle ':dotzsh:*:*' color 'no'
    zstyle ':dotzsh:module:prompt' theme 'off'
fi

if [[ -s "${ZPLUG_HOME}/init.zsh" ]]
then
    export ZPLUG_LOADFILE="${ZDOTDIR:-$HOME}/.zsh/zplug.zsh"
    source "${ZPLUG_HOME}/init.zsh"

    if ! zplug check --verbose; then
        printf "Install? [y/N]: "
        if read -q; then
            echo; zplug install
        fi
        echo
    fi
    # zplug load
    zplug load --verbose

fi
